# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LLSIFTomodachi' do
  pod 'AppCenter/Crashes', '~> 2.1.0'
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'

  # Pods for LLSIFTomodachi

  platform :ios, '9.0'
  target 'LLSIFTomodachiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LLSIFTomodachi-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LLSIFTomodachi-tvOS

  target 'LLSIFTomodachi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
