require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'LLSIFTomodachi' do
  # Pods for LLSIFTomodachiApp
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  pod 'Firebase/Core', '~> 6.13.0'
  pod 'Firebase/Messaging', '~> 6.13.0'

  target 'LLSIFTomodachiTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!('Flipper' => '0.62.0')
  post_install do |installer|
    flipper_post_install(installer)
  end
end
