# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LLSIFTomodachi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LLSIFTomodachi
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'AppCenter/Crashes', '~> 1.11.0'
  pod 'AppCenter/Analytics', '~> 1.11.0'
  pod 'AppCenterReactNativeShared', '~> 1.10.0'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
  pod 'GoogleAppMeasurement', '~> 5.3.0'

  target 'LLSIFTomodachi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LLSIFTomodachiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
